image: 10.0.0.101:5000/ubuntu-loaded

stages:
  - build
  - verify
  - graduate
  - version

build:
  stage: build
  tags:
    - docker
  before_script:
    - git config --global user.email "compulsivecoder@gmail.com"
    - git config --global user.name "CompulsiveCoder"
    - git checkout "$CI_COMMIT_BRANCH"
    - bash pull.sh
  script:
    - bash init.sh
    - bash build.sh
    
test-unit:
  stage: verify
  tags:
    - docker
  before_script:
    - git config --global user.email "compulsivecoder@gmail.com"
    - git config --global user.name "CompulsiveCoder"
    - git checkout "$CI_COMMIT_BRANCH"
    - bash pull.sh
    - cat full-version.txt
  script:
    - bash test.sh
  dependencies:
    - build
    
graduate:
  stage: graduate
  tags:
    - docker
  before_script:
    - git remote set-url origin https://$GHTOKEN@github.com/GrowSense/Index.git
    - git remote add lan http://Internal:$GLTOKEN@10.0.0.101:180/growsense/index.git || git remote set-url lan http://Internal:$GLTOKEN@10.0.0.101:180/growsense/index.git
    - git config --global user.email "compulsivecoder@gmail.com"
    - git config --global user.name "CompulsiveCoder"
    - git checkout "$CI_COMMIT_BRANCH"
    - bash pull.sh
  script:
    - bash clean.sh
    - bash graduate.sh
  dependencies:
    - build

version:
  stage: version
  tags:
    - docker
  before_script:
    - git remote set-url origin https://$GHTOKEN@github.com/GrowSense/Index.git
    - git remote add lan http://Internal:$GLTOKEN@10.0.0.101:180/growsense/index.git || git remote set-url lan http://Internal:$GLTOKEN@10.0.0.101:180/growsense/index.git
    - git config --global user.email "compulsivecoder@gmail.com"
    - git config --global user.name "CompulsiveCoder"
    - git checkout "$CI_COMMIT_BRANCH"
    - bash pull.sh
  script:
    - bash increment-version.sh
    - bash push-version.sh
