//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowSense.SystemManager.WWW {
	
	
	public partial class CalibrateSoilMoistureSensor {
		
		protected System.Web.UI.WebControls.Content contentPlaceHolderContent;
		
		public new GrowSense.SystemManager.Master Master {
			get {
				return ((GrowSense.SystemManager.Master)(base.Master));
			}
		}
	}
}
