// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace GrowSense.SystemManager {
	
	
	public partial class ComputersPage {
		
		protected System.Web.UI.WebControls.Content contentPlaceHolderContent;
		
		public new GrowSense.SystemManager.Master Master {
			get {
				return ((GrowSense.SystemManager.Master)(base.Master));
			}
		}
	}
}
