// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace GrowSense.SystemManager.WWW {
	
	
	public partial class EditVentilator {
		
		protected System.Web.UI.WebControls.Content contentPlaceHolderContent;
		
		protected System.Web.UI.WebControls.DropDownList FanMode;
		
		protected System.Web.UI.WebControls.DropDownList MinimumTemperature;
		
		protected System.Web.UI.WebControls.DropDownList MaximumTemperature;
		
		protected System.Web.UI.WebControls.DropDownList MinimumHumidity;
		
		protected System.Web.UI.WebControls.DropDownList MaximumHumidity;
		
		public new GrowSense.SystemManager.Master Master {
			get {
				return ((GrowSense.SystemManager.Master)(base.Master));
			}
		}
	}
}
