// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace GrowSense.SystemManager.WWW {
	
	
	public partial class EditSoilMoistureMonitor {
		
		protected System.Web.UI.WebControls.Content contentPlaceHolderContent;
		
		protected System.Web.UI.WebControls.DropDownList DryCalibration;
		
		protected System.Web.UI.WebControls.DropDownList WetCalibration;
		
		protected System.Web.UI.WebControls.DropDownList BoardType;
	}
}
