// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace GrowSense.SystemManager.WWW {
	
	
	public partial class EditIlluminator {
		
		protected System.Web.UI.WebControls.Content contentPlaceHolderContent;
		
		protected System.Web.UI.WebControls.DropDownList LightMode;
		
		protected System.Web.UI.WebControls.DropDownList TimerStartHour;
		
		protected System.Web.UI.WebControls.DropDownList TimerStartMinute;
		
		protected System.Web.UI.WebControls.DropDownList TimerStopHour;
		
		protected System.Web.UI.WebControls.DropDownList TimerStopMinute;
		
		protected System.Web.UI.WebControls.DropDownList Threshold;
		
		protected System.Web.UI.WebControls.DropDownList DarkCalibration;
		
		protected System.Web.UI.WebControls.DropDownList BrightCalibration;
		
		public new GrowSense.SystemManager.Master Master {
			get {
				return ((GrowSense.SystemManager.Master)(base.Master));
			}
		}
	}
}
