// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace GrowSense.SystemManager.WWW {
	
	
	public partial class NetworkSettings {
		
		protected System.Web.UI.WebControls.Content contentPlaceHolderContent;
		
		protected System.Web.UI.WebControls.CheckBox ActivateEthernet;
		
		protected System.Web.UI.WebControls.CheckBox ActivateWiFiNetwork;
		
		protected System.Web.UI.WebControls.TextBox WiFiName;
		
		protected System.Web.UI.WebControls.TextBox WiFiPass;
		
		protected System.Web.UI.WebControls.CheckBox ActivateWiFiHotSpot;
		
		protected System.Web.UI.WebControls.TextBox HotSpotName;
		
		protected System.Web.UI.WebControls.TextBox HotSpotPass;
		
		protected System.Web.UI.WebControls.PlaceHolder ComputerFieldsHolder;
		
		public new GrowSense.SystemManager.Master Master {
			get {
				return ((GrowSense.SystemManager.Master)(base.Master));
			}
		}
	}
}
